### ISSUE TITLE
Support arbitrary encodings in CSV uploads

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#32] opened 2016-05-26 17:40 UTC
ATM csv processing is being done client-side, which means it either needs a client-side solution, or to move server side.  If moved server side, then the octopus sheets module can be used via command line utility:

Using https://github.com/CottageLabs/python-cl-api

See https://github.com/richard-jones/magnificent-octopus/blob/8f8d91869e7b1a1f2ef969546a14ac99f4c9fba9/octopus/modules/sheets/README.md#csv

**Comment by emanuil-tolev** [comment] 2016-06-14 13:54
@markmacgillivray Do you think we'll be able to have a crack at this this week (e.g. before Fri 17th)? I know OR16 is ongoing hence the question.

**Comment by markmacgillivray** [comment] 2016-06-14 14:08
I've done all the other things I needed to do now, so this is the next
Lantern thing on my list. The options are that the UI js gets improved to
deal with encodings, or the clcsv stuff gets run as an API that can just be
POSTed to, and return a tidied json list of rows that the UI can then work
with.

Richard says he has already done the work of making the clcsv easily
callable - could you look at installing that on a machine somewhere (not my
test machine or the ones running the API, but perhaps a new octopus-service
machine) and make it so that it exposes an API that allows us to call those
internal functions of octopus easily? There is no need for it to have any
cleverness or security - if that is necessary we could just pipe requests
from the actual API to the octopus machine over internal network and close
the octopus service machine from public network.

I will proceed with seeing how much better the UI-side code can get at
handling the problem. That would leave us with two options to choose from
for this particular problem, and even if we did not use the octopus-service
to solve this problem, any work you do in having the octopus methods easily
callable via an API would enable us to just always have a running octopus
service that the other API / UI service can easily call when necessary,
then any useful dev that continues within octopus could be easily deployed
to the octopus-service machine.

**Comment by emanuil-tolev** [comment] 2016-06-14 16:39
> Richard says he has already done the work of making the clcsv easily
> callable - could you look at installing that on a machine somewhere (not my
> test machine or the ones running the API, but perhaps a new octopus-service
> machine) and make it so that it exposes an API that allows us to call those
> internal functions of octopus easily?

Aah, ok - currently they are only command line scripts.. would it be possible to use these (by putting the python app on each machine)? The main reason is soon as you read in the file with JS into a string, the encoding problem has already occurred. If we do it via the network we'd have to tackle the problem of "send the file as untouched as possible". Could it be easier to ask Node to pass the file to the cmdline script already available? (e.g. https://github.com/richard-jones/magnificent-octopus/blob/8f8d91869e7b1a1f2ef969546a14ac99f4c9fba9/octopus/modules/sheets/README.md#csv )

**Comment by markmacgillivray** [comment] 2016-06-14 16:53
I am not proposing to read it with JS into a string. I am proposing to POST
it in a UI html form to an API endpoint that will receive it, and for it to
return the records as JSON.

I know that so far it is just a command line, that is why I'm wondering if
you can update it and run it on an octopus-service machine so that we can
just use it like an API, to this and any other useful function the octopus
library could provide. I don't want to have to maintain all the
dependencies of octopus on every machine that runs the node API code.

**Comment by emanuil-tolev** [comment] 2016-06-14 17:13
OK, so this new endpoint would just receive one file (as a normal "HTML form file upload") and return a JSON list, in which each object will represent 1 row of the CSV, and each key in each object will correspond to a column. Like

```
[
  {
    "DOI": "x",
    "PMID": "",
    "University": "UoB"
  },
  {
    "DOI": "",
    "PMID": "9",
    "University": ""
  }
]
```

**Comment by markmacgillivray** [comment] 2016-06-14 20:02
Yeah I think so. And possibly it would be useful to be able to pass params
into it too via the query params for example. And ideally this approach
would be generic so we could easily deploy on octopus-service machine that
takes API calls and returns octopus function outputs.

**Comment by markmacgillivray** [comment] 2016-06-15 11:49
Do we have any example files containing encodings that we have seen people submit? I think there was one from wellcome, please add it to this issue.

Also, what is it we are trying to achieve with our output? If an incoming file is not utf8, and we turn it into utf8, and then send it back to the client as utf8, there is technically nothing wrong. Is the aim to actually return content to the user in the encoding they uploaded in, rather than in utf8? What did the old lantern actually do when the incoming file was not utf8?

**Comment by markmacgillivray** [comment] 2016-06-15 11:50
@emanuil-tolev adding a ping to you re. the above point of an example file to be added to this issue please

**Comment by emanuil-tolev** [comment] 2016-06-15 12:04
We always return utf8.

> What did the old lantern actually do when the incoming file was not utf8?

It guessed the encoding so that the file is read in correctly, and output utf8 back to the client. Effectively converting encoding "x" to utf8 without munging the characters.

**Comment by emanuil-tolev** [comment] 2016-06-17 18:38
@markmacgillivray as you can probably guess by the time, I ran into some serious problems. 

> so this new endpoint would just receive one file (as a normal "HTML form file upload") and return a JSON list

I don't think this is feasible right now, or even advisable. The Python codebase's way of parsing a CSV requires a set spec, and is re-doing work that Lantern does very well already (all the extra column parsing / ignoring / what have you, that you wrote before, and enhanced during csvconf '16). That'd be a a fair regression in terms of features without redoing all that work in the Python codebase.

However, we still need the damn re-coding into UTF-8 from [whatever encoding]. So I managed to write an endpoint that takes a CSV, does all the clever stuff and returns _one big UTF-8 encoded string_ over the network.

http://python-api-dev.cottagelabs.com/

And you POST to  http://python-api-dev.cottagelabs.com/csv2utf8str .

If you'd like to troubleshoot at any time manually with curl, `curl -s -XPOST -F "file=@test.csv" http://python-api-dev.cottagelabs.com/csv2utf8str`.

This is the last remaining (afaik) major issue on the wellcome project, since you handled all the UI ones (thanks!) and I _think_ the licence problems should be sorted out.

Now, since it doesn't parse everything, it can't replace the entirety of https://github.com/CottageLabs/cl/blob/master/static/wellcome/wellcome.js . But I'm thinking:
1. we leave all of that stuff in to show a row count
2. but, at https://github.com/CottageLabs/cl/blob/master/static/wellcome/wellcome.js#L210 instead of sending the payload to lantern, we first POST it to http://python-api-dev.cottagelabs.com/csv2utf8str and we do something about potential HTTP 500 errors
3. and we use the output of step 2 to send to lantern

Now the question is, do you think this could possibly work?

**Comment by emanuil-tolev** [comment] 2016-06-17 18:44
Test file minimum example: this file definitely breaks (special char wise) on wellcome.test.cottagelabs.com and definitely works on compliance.cottagelabs.com .

[unicode_test.csv.zip](https://github.com/CottageLabs/LanternPM/files/321087/unicode_test.csv.zip)

**Comment by markmacgillivray** [comment] 2016-06-17 18:46
I had never intended to get rid of wellcome.js (or lantern.js). The
intention was only to POST a file from a form to an endpoint that would
pass things into octopus and provide back a JSON object. Any configs that
are required could go in as query params, I think I suggested already. The
idea of making octopus code available over an API is supposed to be a
generally useful one. I don't think running yet another separate tool to do
this stuff is a good idea. I have been making OK progress with doing this
browser-side anyway, so for now it is probably best to just stick to what I
am doing on the client. The more general issue of making octopus
functionality available over an API can be an ongoing thing to solve. I'm
not sure it should be so complicated as it seems to be becoming.

Thanks for the test file. I will try that with the changes I am working on.

**Comment by emanuil-tolev** [comment] 2016-06-17 18:54
> The more general issue of making octopus
> functionality available over an API can be an ongoing thing to solve. I'm
> not sure it should be so complicated as it seems to be becoming.

The issue isn't making that available, it's that the functionality I can expose is inferior to what the current combo of (wellcome.js + the lantern code) does. Octopus' code is capable of doing the encoding stuff very very well, but its CSV-into-list-of-objects parsing code is not as flexible. As I said it requires a specific "spec", in which _all_ columns expected in the incoming CSV are defined. The new combo of (wellcome.js file + meteor lantern code) deals with any column thrown at it.

The code in octopus could be enhanced to deal with variable columns, but that's a more complicated thing to do than I had/have time for before the end of this particular project. Long-term maybe it is a good idea. And it is definitely a good idea to expose all of octopus' features via an API. It's just that in this case we need 2 features - handling encoding, and column-flexible CSV parsing, and it only has the encoding feature.

**Comment by emanuil-tolev** [comment] 2016-06-17 18:56
> I have been making OK progress with doing this
> browser-side anyway, so for now it is probably best to just stick to what I
> am doing on the client.

That's great news! I'll have to provide a project update Mon morning so I'll probably need to say we need a few more days to figure the encoding stuff out.

**Comment by markmacgillivray** [comment] 2016-06-17 18:57
OK, so yes just leave the octopus-via-API issue as an ongoing thing to work
on, and generally useful for things even if not this. For this problem,
hopefully I can do it well enough client-side. I may get it done by Monday
morning, but if not then yeah, it will be a few days.

**Comment by markmacgillivray** [comment] 2016-06-18 00:48
The test file now works on wellcome.test.cottagelabs.com. Are there any others to test?

**Comment by emanuil-tolev** [comment] 2016-06-19 18:42
This one.

[unicode_test2_results.zip](https://github.com/CottageLabs/LanternPM/files/322449/unicode_test2_results.zip)

Are we not supposed to get Author(s) where this isn't supplied? Perhaps that's not working just for this record for some reason..? Cecy's original record had an "Author(s)" column which looks like it came out of one of our tools (despite being in her upload - must have stitched sheets together or something).

**Comment by richard-jones** [comment] 2016-06-24 07:50
I should say, just for info, that the octopus csv parser is in layers, and only the bottom layer is required to parse UTF-8 into a rectangular grid.  The top layer, which does the interpretation into json, currently only consists of one plugin which enforces good structure on the underlying table, but it would be trivial to write a plugin which just used the first row as a header and returned whatever was in that column.

**Comment by richard-jones** [comment] 2016-06-24 07:51
sorry, parse the bits into a rectangular grid, whatever the encoding (not just UTF-8).

If this is required, I can provide the assistance to make it happen.

**Comment by markmacgillivray** [comment] 2016-06-29 16:02
I think we have this covered now with the client-side updates. Closing.

**Closed as completed by markmacgillivray** 2016-06-29 16:02 UTC
